name: CI
on:
  push:
     branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.13.0
      - name: "Run a on-line script"
        run: echo Hello, world!
